name: Tinh Diem RS Hang Ngay

on:
  schedule:
    - cron: '30 8 * * 1-5'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Check out kho luu tru
      uses: actions/checkout@v4 # Đã nâng cấp lên v4

    - name: Cai dat Python
      uses: actions/setup-python@v5 # Đã nâng cấp lên v5
      with:
        python-version: '3.10'

    - name: Cai dat thu vien
      run: pip install -r requirements.txt

    - name: Chay tinh toan RS
      run: python main.py

    - name: Luu file du lieu vao GitHub
      uses: stefanzweifel/git-auto-commit-action@v5 # Đã nâng cấp lên v5
      with:
        commit_message: "Tu dong cap nhat diem RS"
        file_pattern: data_rs.json
